<div class="azure_settings_block" style="display:none;">
  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
          <label for="baseUrl-azure"><?php echo __('Destination URL', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'baseUrl-azure', 'http://mystaticsite.com', '', ''); ?><br>

          <p><i><?php echo __("Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http, https and protocol relative URLs.", 'static-html-output-plugin');?></i></p> 
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="azStorageAccountName"><?php echo __('Storage account name', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'azStorageAccountName', 'Storage account name', '', ''); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="azContainerName"><?php echo __('Container name', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'azContainerName', 'Container name', '', ''); ?><br>

          <p><i>For <code>$web</code>, enter it as <code>$web</code></i></p>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="azAccessKey"><?php echo __('Access Key', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'azAccessKey', 'Access Key', '', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="azPath"><?php echo __('Subdirectory', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'azPath', 'Path within storage container', '', ''); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="az_test"><?php echo __('Test Azure Settings', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <button id="azure-test-button" type="button" class="btn-primary button">Test Azure Settings</button>
        </td>
      </tr>
    </tbody>
  </table>
</div>
